apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: tracing
  namespace: {{ .Release.Namespace}}
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://zipkin.{{ .Release.Namespace }}.svc.cluster.local:9411/api/v2/spans"